### ISSUE TITLE
Step 2 confusion 

### ISSUE THREAD

**Issue by bibberp** [klatka/nc-talk-bot-component#11]
Hi, I think my inexperience with this stuff is showing.. I want to set up a two way bot and I’m confused what I need to do in step 2. I’m assuming that I skip all of the steps for the one way communication, and all the following steps look pretty straightforward but for step 2 I’m not sure where I need to make my config entry.

**Comment by bibberp** [comment]
I think I got it, realized I needed to add it as an integration

**Comment by klatka** [comment]
I updated the description, hoping to make it easier :)
