### ISSUE TITLE
how to use entities values and/or states out of entities within the notify.nctalkbot action

### ISSUE THREAD

**Issue by gklank** [klatka/nc-talk-bot-component#23]
Hi,

I looking for a possibility to use something like:
{{state_attr("binary_sensor.wassermelder_hobbyraum_alarmzustand", "friendly_name")}}
or
{{states("binary_sensor.wassermelder_vorratsraum_alarmzustand")}}

in the notify.nctalkbot action. Could be in the "message" or "title" section, whereever is possible.

Regards,

Gerhard

**Comment by klatka** [comment]
You are talking about templates: https://www.home-assistant.io/docs/configuration/templating/

In your case an example would be:
```
action: notify.nctalkbot
data:
  message: >
    Der Status von {{ state_attr("binary_sensor.wassermelder_hobbyraum_alarmzustand", "friendly_name") }} ist 
    {{ states("binary_sensor.wassermelder_vorratsraum_alarmzustand") }}
```
